import type {
  Campaign,
  Church,
  ChurchStaffMember,
  Donation,
  FundBreakdown,
  GivingFund,
  GivingSummary,
  GivingTrendPoint,
  Member,
  PaymentMethodSummary,
  RecurringGift,
} from "./types";

export const demoChurch = {
  id: "church_harbour_grace",
  slug: "harbour-grace",
  name: "Harbour Grace Church",
  legalName: "Harbour Grace Community Church",
  email: "hello@harbourgrace.example",
  phone: "+1 (246) 555-0142",
  address: "Bridgetown, Saint Michael, Barbados",
  timezone: "America/Barbados",
  status: "onboarding",
  defaultCurrency: "BBD",
  supportedCurrencies: ["BBD", "USD"],
  branding: {
    primaryColor: "#173F3A",
    accentColor: "#D9A441",
    logoUrl: null,
    thankYouMessage:
      "Thank you for giving generously. Your gift helps us serve our church and community.",
  },
  paymentConnection: {
    providerKey: "mock-barbados-gateway",
    externalMerchantReference: null,
    status: "pending",
    settlementMode: "direct_to_church",
    connectedAt: null,
  },
  subscription: {
    status: "incomplete",
    planName: "Church Essentials",
    monthlyPrice: { amountMinor: 9_900, currency: "USD" },
    renewsAt: null,
  },
  createdAt: "2026-07-18T13:00:00.000Z",
} satisfies Church;

export const demoFunds = [
  {
    id: "fund_tithes",
    churchId: demoChurch.id,
    name: "Tithes",
    slug: "tithes",
    description: "Regular giving in support of the life and ministry of our church.",
    isDefault: true,
    isActive: true,
    displayOrder: 1,
  },
  {
    id: "fund_general",
    churchId: demoChurch.id,
    name: "General Offering",
    slug: "general-offering",
    description: "Support the church's day-to-day ministry and community work.",
    isDefault: false,
    isActive: true,
    displayOrder: 2,
  },
  {
    id: "fund_missions",
    churchId: demoChurch.id,
    name: "Missions",
    slug: "missions",
    description: "Help our local and regional mission partners reach more people.",
    isDefault: false,
    isActive: true,
    displayOrder: 3,
  },
  {
    id: "fund_building",
    churchId: demoChurch.id,
    name: "Building Fund",
    slug: "building-fund",
    description: "Contribute to improvements to our worship and community spaces.",
    isDefault: false,
    isActive: true,
    displayOrder: 4,
  },
  {
    id: "fund_youth",
    churchId: demoChurch.id,
    name: "Youth Ministry",
    slug: "youth-ministry",
    description: "Create safe, meaningful programmes for children and young people.",
    isDefault: false,
    isActive: true,
    displayOrder: 5,
  },
] satisfies readonly GivingFund[];

export const demoCampaigns = [
  {
    id: "campaign_community_centre",
    churchId: demoChurch.id,
    fundId: "fund_building",
    name: "Community Care Centre",
    slug: "community-care-centre",
    description:
      "Help us renovate a welcoming space for after-school programmes, counselling and food support.",
    status: "active",
    goal: { amountMinor: 5_000_000, currency: "BBD" },
    raised: { amountMinor: 3_425_000, currency: "BBD" },
    startsAt: "2026-06-01T04:00:00.000Z",
    endsAt: "2026-12-31T03:59:59.000Z",
    imageUrl: null,
  },
  {
    id: "campaign_school_supplies",
    churchId: demoChurch.id,
    fundId: "fund_youth",
    name: "Back-to-School Drive",
    slug: "back-to-school-drive",
    description:
      "Provide school supplies and uniforms to children in our community.",
    status: "active",
    goal: { amountMinor: 1_200_000, currency: "BBD" },
    raised: { amountMinor: 785_000, currency: "BBD" },
    startsAt: "2026-07-05T04:00:00.000Z",
    endsAt: "2026-09-05T03:59:59.000Z",
    imageUrl: null,
  },
] satisfies readonly Campaign[];

export const demoMembers = [
  {
    id: "member_alicia",
    churchId: demoChurch.id,
    firstName: "Alicia",
    lastName: "Clarke",
    email: "alicia.clarke@example.com",
    phone: "+1 (246) 555-0178",
    joinedAt: "2026-06-08T15:24:00.000Z",
    emailVerifiedAt: "2026-06-08T15:28:00.000Z",
  },
  {
    id: "member_daniel",
    churchId: demoChurch.id,
    firstName: "Daniel",
    lastName: "Browne",
    email: "daniel.browne@example.com",
    phone: null,
    joinedAt: "2026-06-19T21:10:00.000Z",
    emailVerifiedAt: "2026-06-19T21:15:00.000Z",
  },
  {
    id: "member_naomi",
    churchId: demoChurch.id,
    firstName: "Naomi",
    lastName: "King",
    email: "naomi.king@example.com",
    phone: "+1 (246) 555-0191",
    joinedAt: "2026-07-03T12:45:00.000Z",
    emailVerifiedAt: "2026-07-03T12:48:00.000Z",
  },
  {
    id: "member_marcus",
    churchId: demoChurch.id,
    firstName: "Marcus",
    lastName: "Forde",
    email: "marcus.forde@example.com",
    phone: null,
    joinedAt: "2026-07-27T14:11:00.000Z",
    emailVerifiedAt: "2026-07-27T14:14:00.000Z",
  },
] satisfies readonly Member[];

export const demoChurchStaff = [
  {
    id: "staff_miriam",
    churchId: demoChurch.id,
    firstName: "Miriam",
    lastName: "Jordan",
    email: "miriam@harbourgrace.example",
    role: "church_owner",
    status: "active",
    joinedAt: "2026-07-18T13:15:00.000Z",
  },
  {
    id: "staff_andre",
    churchId: demoChurch.id,
    firstName: "Andre",
    lastName: "Best",
    email: "andre@harbourgrace.example",
    role: "finance_admin",
    status: "active",
    joinedAt: "2026-07-20T16:42:00.000Z",
  },
  {
    id: "staff_keisha",
    churchId: demoChurch.id,
    firstName: "Keisha",
    lastName: "Grant",
    email: "keisha@harbourgrace.example",
    role: "staff",
    status: "active",
    joinedAt: "2026-07-26T18:03:00.000Z",
  },
] satisfies readonly ChurchStaffMember[];

const visa4242 = {
  id: "pm_demo_visa_4242",
  type: "card",
  brand: "Visa",
  last4: "4242",
  expiryMonth: 9,
  expiryYear: 2029,
  isDefault: true,
} satisfies PaymentMethodSummary;

const mastercard4444 = {
  id: "pm_demo_mastercard_4444",
  type: "card",
  brand: "Mastercard",
  last4: "4444",
  expiryMonth: 4,
  expiryYear: 2030,
  isDefault: true,
} satisfies PaymentMethodSummary;

export const demoRecurringGifts = [
  {
    id: "recurring_alicia_tithes",
    churchId: demoChurch.id,
    memberId: "member_alicia",
    fundId: "fund_tithes",
    campaignId: null,
    amount: { amountMinor: 25_000, currency: "BBD" },
    frequency: "weekly",
    status: "active",
    paymentMethod: visa4242,
    providerScheduleReference: "mock_schedule_alicia",
    startedAt: "2026-06-14T13:00:00.000Z",
    nextChargeAt: "2026-08-23T13:00:00.000Z",
    pausedAt: null,
    cancelledAt: null,
  },
  {
    id: "recurring_daniel_tithes",
    churchId: demoChurch.id,
    memberId: "member_daniel",
    fundId: "fund_tithes",
    campaignId: null,
    amount: { amountMinor: 10_000, currency: "BBD" },
    frequency: "monthly",
    status: "active",
    paymentMethod: mastercard4444,
    providerScheduleReference: "mock_schedule_daniel",
    startedAt: "2026-06-19T21:12:00.000Z",
    nextChargeAt: "2026-08-19T21:12:00.000Z",
    pausedAt: null,
    cancelledAt: null,
  },
] satisfies readonly RecurringGift[];

export const demoDonations = [
  {
    id: "donation_1006",
    churchId: demoChurch.id,
    fundId: "fund_tithes",
    campaignId: null,
    recurringGiftId: "recurring_alicia_tithes",
    donor: {
      memberId: "member_alicia",
      name: "Alicia Clarke",
      email: "alicia.clarke@example.com",
    },
    amount: { amountMinor: 25_000, currency: "BBD" },
    processingFee: { amountMinor: 775, currency: "BBD" },
    netAmount: { amountMinor: 24_225, currency: "BBD" },
    frequency: "weekly",
    status: "succeeded",
    paymentMethod: visa4242,
    providerPaymentReference: "mock_pay_1006",
    receiptNumber: "HGC-2026-001006",
    message: "With gratitude.",
    createdAt: "2026-08-16T13:04:00.000Z",
    settledAt: "2026-08-17T18:00:00.000Z",
  },
  {
    id: "donation_1005",
    churchId: demoChurch.id,
    fundId: "fund_tithes",
    campaignId: null,
    recurringGiftId: null,
    donor: {
      memberId: null,
      name: "Janelle Moore",
      email: "janelle.moore@example.com",
    },
    amount: { amountMinor: 20_000, currency: "BBD" },
    processingFee: { amountMinor: 630, currency: "BBD" },
    netAmount: { amountMinor: 19_370, currency: "BBD" },
    frequency: "one_time",
    status: "succeeded",
    paymentMethod: null,
    providerPaymentReference: "mock_pay_1005",
    receiptNumber: "HGC-2026-001005",
    message: null,
    createdAt: "2026-08-16T12:18:00.000Z",
    settledAt: "2026-08-17T18:00:00.000Z",
  },
  {
    id: "donation_1004",
    churchId: demoChurch.id,
    fundId: "fund_building",
    campaignId: "campaign_community_centre",
    recurringGiftId: null,
    donor: {
      memberId: "member_naomi",
      name: "Naomi King",
      email: "naomi.king@example.com",
    },
    amount: { amountMinor: 50_000, currency: "BBD" },
    processingFee: { amountMinor: 1_525, currency: "BBD" },
    netAmount: { amountMinor: 48_475, currency: "BBD" },
    frequency: "one_time",
    status: "succeeded",
    paymentMethod: visa4242,
    providerPaymentReference: "mock_pay_1004",
    receiptNumber: "HGC-2026-001004",
    message: "For the new community space.",
    createdAt: "2026-08-15T19:32:00.000Z",
    settledAt: "2026-08-17T18:00:00.000Z",
  },
  {
    id: "donation_1003",
    churchId: demoChurch.id,
    fundId: "fund_tithes",
    campaignId: null,
    recurringGiftId: "recurring_daniel_tithes",
    donor: {
      memberId: "member_daniel",
      name: "Daniel Browne",
      email: "daniel.browne@example.com",
    },
    amount: { amountMinor: 10_000, currency: "BBD" },
    processingFee: { amountMinor: 340, currency: "BBD" },
    netAmount: { amountMinor: 9_660, currency: "BBD" },
    frequency: "monthly",
    status: "succeeded",
    paymentMethod: mastercard4444,
    providerPaymentReference: "mock_pay_1003",
    receiptNumber: "HGC-2026-001003",
    message: null,
    createdAt: "2026-08-14T21:12:00.000Z",
    settledAt: "2026-08-15T18:00:00.000Z",
  },
  {
    id: "donation_1002",
    churchId: demoChurch.id,
    fundId: "fund_missions",
    campaignId: null,
    recurringGiftId: null,
    donor: {
      memberId: "member_marcus",
      name: "Marcus Forde",
      email: "marcus.forde@example.com",
    },
    amount: { amountMinor: 7_500, currency: "BBD" },
    processingFee: { amountMinor: 265, currency: "BBD" },
    netAmount: { amountMinor: 7_235, currency: "BBD" },
    frequency: "one_time",
    status: "succeeded",
    paymentMethod: null,
    providerPaymentReference: "mock_pay_1002",
    receiptNumber: "HGC-2026-001002",
    message: null,
    createdAt: "2026-08-13T16:48:00.000Z",
    settledAt: "2026-08-14T18:00:00.000Z",
  },
  {
    id: "donation_1001",
    churchId: demoChurch.id,
    fundId: "fund_building",
    campaignId: "campaign_community_centre",
    recurringGiftId: null,
    donor: {
      memberId: null,
      name: "Samuel Hinds",
      email: "samuel.hinds@example.com",
    },
    amount: { amountMinor: 15_000, currency: "BBD" },
    processingFee: { amountMinor: 485, currency: "BBD" },
    netAmount: { amountMinor: 14_515, currency: "BBD" },
    frequency: "one_time",
    status: "succeeded",
    paymentMethod: null,
    providerPaymentReference: "mock_pay_1001",
    receiptNumber: "HGC-2026-001001",
    message: "God bless this work.",
    createdAt: "2026-08-11T22:06:00.000Z",
    settledAt: "2026-08-12T18:00:00.000Z",
  },
] satisfies readonly Donation[];

export const demoGivingSummary = {
  total: { amountMinor: 127_500, currency: "BBD" },
  transactionCount: 6,
  activeRecurringCount: 2,
  uniqueDonorCount: 6,
  periodStart: "2026-08-10T04:00:00.000Z",
  periodEnd: "2026-08-17T03:59:59.000Z",
} satisfies GivingSummary;

export const demoGivingTrend = [
  { label: "13 Jul", total: { amountMinor: 86_500, currency: "BBD" } },
  { label: "20 Jul", total: { amountMinor: 112_000, currency: "BBD" } },
  { label: "27 Jul", total: { amountMinor: 98_500, currency: "BBD" } },
  { label: "3 Aug", total: { amountMinor: 141_000, currency: "BBD" } },
  { label: "10 Aug", total: { amountMinor: 119_500, currency: "BBD" } },
  { label: "17 Aug", total: { amountMinor: 127_500, currency: "BBD" } },
] satisfies readonly GivingTrendPoint[];

export const demoFundBreakdown = [
  {
    fundId: "fund_tithes",
    fundName: "Tithes",
    total: { amountMinor: 55_000, currency: "BBD" },
    percentage: 43.1,
  },
  {
    fundId: "fund_building",
    fundName: "Building Fund",
    total: { amountMinor: 65_000, currency: "BBD" },
    percentage: 51,
  },
  {
    fundId: "fund_missions",
    fundName: "Missions",
    total: { amountMinor: 7_500, currency: "BBD" },
    percentage: 5.9,
  },
] satisfies readonly FundBreakdown[];

export const demoGivingUrl = `/give/${demoChurch.slug}` as const;
export const demoQrCode = "hgc-7v2q9mx4" as const;
